language: node_js
node_js:
  - 12
before_script:
  - npm install
script:
  - npm run build
  - chmod 600 ./2019_2_Pirogi.pem
  - ssh-keyscan -H 167.71.5.55 >> ~/.ssh/known_hosts
  - scp -i ./2019_2_Pirogi.pem -r ./dist/* root@167.71.5.55:/cinsear/frontend/dist

before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in 2019_2_Pirogi.pem.enc -out ./2019_2_Pirogi.pem -d

