import './css/reset.sass'
import './css/fonts.sass'
import './css/variables.sass'

import './components/main/main.sass'
import './components/text/text.sass'
import './components/list/list.sass'
import './components/hr/hr.sass'
import './components/vr/vr.sass'
import './components/form/form.sass'
import './components/input/input.sass'
import './components/textarea/textarea.sass'
import './components/button/button.sass'
import './components/logo/logo.sass'

import './components/top/top.sass'
import './components/navbar/navbar.sass'

import './pages/admin/admin.sass'
import './pages/film/film.sass'
import './pages/error/error.sass'
import './pages/search/search.sass'